version: '3.8'

services:
  django:
    build: .
    volumes:
      - .:/thatheavydiscord
    ports:
      - 8000:8000
    image: django
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=hharting14
      - POSTGRES_PASSWORD=hh
    container_name: postgres
